
###
GET http://localhost:3005/api/users HTTP/1.1
content-type: application/json


###
POST http://localhost:3005/api/signup HTTP/1.1
content-type: application/json

{
    "email": "temka@temka.mn",
    "password": "Temka1234.",
    "repassword": "Temka1234."
}


###
POST http://localhost:3005/api/signin HTTP/1.1
content-type: application/json

{
    "email": "temka@temka.mn",
    "password": "Temka1234."
}

###
GET http://localhost:3005/api/categories HTTP/1.1
content-type: application/json
Authorization: FAIvtUsgEQziPr6Gf5Rze



###
GET http://localhost:3005/api/categories/1 HTTP/1.1
content-type: application/json
Authorization: FAIvtUsgEQziPr6Gf5Rze

###
POST http://localhost:3005/api/chats HTTP/1.1
content-type: application/json

{
    "name": "Baldan",
    "text": "Hi hoorhnoo"
}
